#!/bin/bash

function main()
{
    IP=$(detectCurrentPublicIP)
    ENTRY=$(detectCurrentDNSEntry)

    if [ "$IP" != "$ENTRY" ]
    then
        exitCritical "Detected IP is $IP but the DNS points to $ENTRY"
    else
        echo "OK - Detected IP $IP matches with the DNS"
        exit 0
    fi
}

function exitCritical()
{
    echo "CRITICAL - $1"
    exit 2
}

function detectCurrentPublicIP()
{
    local IP=`dig -4 +short myip.opendns.com @resolver1.opendns.com`
    echo $IP
}

function detectCurrentDNSEntry()
{
    local entry=`dig +short -4 home.veloc1ty.de`
    echo $entry
}

main
